export const Types = {
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  INCREMENT_ITEM_QTY: "INCREMENT_ITEM_QTY",
  REDUCE_ITEM_QTY: "REDUCE_ITEM_QTY",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
};
